### PR TITLE
Fix translations not loading in some pages

### LINKED ISSUE #117: Bug: i18n not working on staking pages
### Describe the bug

String translations using the `t` function do not work on the staking pages.

### To reproduce

See error in the https://ethereum-org-fork.netlify.app/staking/solo page for example.

### Expected behavior

Translations should work on all pages.

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by pettinarip**
## Description

As we were passing only the `common` namespace to the `serverSideTranslations` function, the rest of the namespaces were not loaded correctly.

This PR adds the necessary namespaces for a given page path/slug on server-side, and reuses the logic in the client-side `Translation` component.

## Related Issue

Fixes #117

### CODE REVIEW

File: src/components/Translation.tsx [hunk 1]
```diff
@@ -19,34 +20,8 @@ const transform = {
 // Renders the translation string for the given translation key `id`. It
 // fallback to English if it doesn't find the given key in the current language
 const Translation = ({ id, options }: Props) => {
-  const [requiredNamespaces, setRequiredNamespaces] = useState<string[]>([])
   const { asPath } = useRouter()
-
-  useEffect(() => {
```
Comment (pettinarip) [inline src/components/Translation.tsx:25]: I've also removed this `useEffect` as it was not needed and was causing a loop. `setState` => `useEffect dep triggered` => `setState again`

File: src/lib/utils/translations.ts [hunk 2]
```diff
@@ -15,3 +15,33 @@ export const isLangRightToLeft = (lang: Lang): boolean => {
...
+  }
+
+  if (path.startsWith("/nft")) {
+    requiredNamespaces = [...requiredNamespaces, "learn-quizzes"]
+  }
+
+  if (path.startsWith("/staking")) {
+    requiredNamespaces = [...requiredNamespaces, "page-staking"]
+  }
+
```
Comment (wackerow) [inline src/lib/utils/translations.ts:45]: @pettinarip 
Looks good, curious if there was a preference for `let` then re-spreading, vs `const` and `.push()` here: 
ie. 
```tsx
const requiredNamespaces: string[] = ["common"]
// ...
if (criteria) { requiredNamespaces.push("namespace") }
```

**Comment by wackerow** [comment]
image

@pettinarip Just looking through, components on the staking/solo page have caught my eye (as they still aren't showing the translated strings)... Looking in the code, it appears we'll need to refactor each individual component to use the new i18n setup (unless I'm missing something). I'll try to keep the review to non-component strings if that's good with you and we can address the components as we go through them. 

(Also, sadly seeing more ToC bugs in that Turkish screenshot above... will investigate)

File: src/lib/utils/translations.ts (hunk 2 above)
Comment (pettinarip) [reply src/lib/utils/translations.ts:45]: No special reason. I think it is just a matter of preference. For example, when you need to push more than just one element to the array, it is kind of annoying to do a double push 🤷🏼 and I'm more used to code with immutable methods.

**Comment by pettinarip** [comment]
> @pettinarip Just looking through, components on the staking/solo page have caught my eye (as they still aren't showing the translated strings)... Looking in the code, it appears we'll need to refactor each individual component to use the new i18n setup (unless I'm missing something). I'll try to keep the review to non-component strings if that's good with you and we can address the components as we go through them.
> 

Good catch @wackerow. Not sure whats going on there. I'll investigate and get back to you.

File: src/lib/utils/translations.ts (hunk 2 above)
Comment (nhsz) [reply src/lib/utils/translations.ts:45]: Same, I usually prefer methods that dont mutate the array like the spread op

**Review by nhsz — APPROVED** [review]
